---
title: "Experimental results"
output: html_notebook
---

The following code summarizes and plots the results out our experiments
```{r util_functions, echo=F, message = F, warn = F}

library(dplyr)
library(readr)
library(tidyr)

merge_csv_fragments <- function(folder_A, folder_B) {
  # Get list of CSV fragment files in the source folder
  csv_files <- list.files(folder_A, pattern = "\\.csv\\.\\d+$", full.names = TRUE)

  # Extract base names and group files
  base_names <- gsub("\\.csv\\.\\d+$", "", basename(csv_files))
  file_groups <- split(csv_files, base_names)

  # Process each group
  for (base_name in names(file_groups)) {
    # Get the files for the current group and sort them by fragment number
    group_files <- file_groups[[base_name]]
    group_files <- group_files[order(as.numeric(gsub(".*\\.csv\\.(\\d+)$", "\\1", group_files)))]

    # Create an empty character vector to store the combined content
    combined_content <- character()

    # Read and concatenate all CSV fragments in the group
    for (file in group_files) {
      file_content <- readLines(file)
      combined_content <- c(combined_content, file_content)
    }

    # Remove duplicate header lines if present
    header <- combined_content[1]
    combined_content <- c(header, combined_content[-1])

    # Define the output file path
    output_file_name <- paste0(base_name, ".csv")
    output_file_path <- file.path(folder_B, output_file_name)

    # Write the combined content to a CSV file in the destination folder
    writeLines(combined_content, output_file_path)

    message("CSV fragments for '", base_name, "' merged and saved to ", output_file_path)
  }
}


euclidean_distance <- function(vec1, vec2) {
  # Check if both vectors have the same length
  if (length(vec1) != length(vec2)) {
    stop("Vectors must have the same length.")
  }

  # Calculate the sum of squared differences
  sum_sq_diff <- sum((vec1 - vec2)^2)

  # Take the square root of the sum of squared differences
  dist <- sqrt(sum_sq_diff)

  return(dist)
}


experiment_from_name <- function(filename){
  pattern <- ".+\\/([A-Za-z0-9]+?)_([A-Za-z0-9]+?)_([A-Za-z0-9_]+)_2024"
  matches <- regexec(pattern, filename)
  captures <- regmatches(filename, matches)

  if (length(captures[[1]]) > 0) {
    components <- captures[[1]][-1]  # Remove the full match
    dataset <- components[1]
    estimator <- components[2]
    experiment_name <- components[3]

    return(list(dataset = dataset, estimator = estimator, experiment_name = experiment_name))
  } else {
    return(list(dataset = NA, estimator = NA, experiment_name = NA))
  }
}
```


```{r load_aggregate_data, echo=F, cache = T, message = F, warning = F}
merge_csv_fragments("results_new","results_aggregated")

files <- list.files("results_aggregated", pattern = "\\.csv", full.names = TRUE)

full_data <- data.frame()
for (file in files){
  data <- read.csv(file)
  params <- data$params
  numeric_params <- (strsplit(gsub("\\[ ?|\\]|\n", "", params), "\\s+"))
  final_estimators <- do.call(rbind, lapply(numeric_params, as.numeric))
  data$params <- final_estimators
  unperturbed_radon_point <- apply(t(data %>% filter(outliers==0, sigma==0) %>% .$params),1,mean)

  data$radon_bias <- apply(data$params,1,function(x){euclidean_distance(x,unperturbed_radon_point)})
  data$params <- NULL
  data$estimators <- list(experiment_from_name(file))
  data <- data %>% unnest_wider(estimators)

  full_data <- bind_rows(data,full_data)
}
full_data

```


Type any R code in the chunk, for example:
```{r, echo = F}
library(tidyverse)
library(ggplot2)

for(dset in unique(full_data$dataset)){
  for(est in unique(full_data$estimator)){
    for(exprmt in unique(full_data$experiment_name)){

      summary_data <- full_data %>%
              filter(experiment_name == exprmt, dataset == dset, estimator == est) %>%
              group_by(outliers,sigma) %>%
              filter(split == 0) %>%
              reframe(
                      mean_auc = mean(auc),
                      auc_low = (mean(auc) - qt(0.975, df=n()-1) * sd(auc) / sqrt(n())),
                      auc_high = (mean(auc) + qt(0.975, df=n()-1) * sd(auc) / sqrt(n())),
                      mean_radon_bias = mean(radon_bias,na.rm = TRUE),
                      radon_bias_low = (mean(radon_bias,na.rm = TRUE) - qt(0.975, df=n()-1) * sd(radon_bias,na.rm = TRUE) / sqrt(n())),
                      radon_bias_high = (mean(radon_bias,na.rm = TRUE) + qt(0.975, df=n()-1) * sd(radon_bias,na.rm = TRUE) / sqrt(n()))
              )
      if(nrow(summary_data) == 0){
        next
      }

      long_summary_data <-  summary_data %>%
              pivot_longer(cols = c(mean_auc, mean_radon_bias),
                           names_to = "measure",
                           values_to = "value") %>%
              mutate(high = ifelse(measure == "mean_auc",auc_high,radon_bias_high),
                     low = ifelse(measure == "mean_auc",auc_low,radon_bias_low))

      if(nrow(long_summary_data) == 0){
        next
      }

      p <- ggplot(long_summary_data, aes(x=outliers, fill=as.factor(sigma))) +
              theme(panel.border = element_rect(color = "black")) +
              geom_line(aes(y=value,color = as.factor(sigma))) +
              geom_ribbon(aes(ymin = low, ymax = high),alpha = 0.2) +
              facet_wrap(~measure,scales = "free_y",
                         strip.position = "left",
                         labeller = labeller(measure = c("mean_auc" = "ROC-AUC","mean_radon_bias" = "Distance to true center"))) +
              # geom_line(aes(y=mean_radon_bias/coeff+offset,color = as.factor(sigma))) +
              # geom_ribbon(aes(ymin = radon_bias_low/coeff+offset, ymax = radon_bias_high/coeff+offset),alpha = 0.2) +
              geom_vline(aes(xintercept = 52, linetype = "κ")) +
              labs(title = paste0(exprmt ," experiment ",est, " Radon-machine on ",dset, " Dataset h= ",ifelse(dset=="codrna",5,3)),
                   x = "Number of outliers",
                   y = "",
                   color = "additive noise (σ)",
                   fill = "additive noise (σ)") +
              scale_linetype_manual(name="κ", labels = "", values= "dashed") +
              theme_minimal() +
              theme(legend.position = "bottom",
                    legend.direction="horizontal",
                    legend.text = element_text(size = 12),  # Adjust legend text size
                    legend.key.width = unit(0.75, "cm"),  # Adjust width of legend keys (color boxes)
                    legend.key.height = unit(0.5, "cm"),
                    axis.text = element_text(size = 14),
                    axis.title = element_text(size = 16),
                    plot.title = element_text(size = 18, face = "bold"),
                    strip.text = element_text(size = 16, vjust =2), # Left-align facet labels
                    axis.text.y = element_text(size = 14, hjust = 0), # Right-align y-axis labels
                    panel.grid.minor = element_blank(),
                    # panel.grid.major = element_blank(),
                    strip.placement = "outside",
                    # Keep the panel border
                    # panel.border = element_rect(color = "gray70", fill = NA, size=0.5),
                    axis.ticks = element_line())
      plot(p)
    }
  }
}
# for (file in files){
#   print(file)
#   data <- read.csv(file)
#   params <- data$params
#
#   # Remove square brackets and split the string by whitespace
#   numeric_params <- (strsplit(gsub("\\[ ?|\\]", "", params), "\\s+"))
#   final_estimators <- do.call(rbind, lapply(numeric_params, as.numeric))
#
#   data$params <- final_estimators
#
#
#   summary_data <- data %>%
#           group_by(outliers,sigma) %>%
#           reframe(
#                   mean_y = mean(auc),
#                   ci_low = pmin(mean(auc) - qt(0.975, df=n()-1) * sd(auc) / sqrt(n()), min(auc)),
#                   ci_high = pmax(mean(auc) + qt(0.975, df=n()-1) * sd(auc) / sqrt(n()), max(auc))
#           )
#
#
#   (ggplot(summary_data %>% filter(sigma %in% c(0,1e-10,1e-5,0.001,0.1,0.5,1,2)), aes(x = outliers, y = mean_y)) +
#           geom_line(aes(color = as.factor(sigma))) +
#           geom_ribbon(aes(ymin = ci_low, ymax = ci_high, fill=as.factor(sigma)), alpha = 0.2) +
#           geom_vline(xintercept = 52, linetype="dashed") +
#           # geom_point(data = data, aes(x = x, y = y), alpha = 0.1) + # optional: to show original data points
#           labs(title = "Linear SVM Radon machine SUSY Dataset height=3",
#                subtitle = file,
#                x = "Number of outliers",
#                y = "ROC-AUC-score") +
#           theme_minimal()) %>% plot()
#
#
#
#   (ggplot(data %>% filter(outliers == 0),
#          aes(x = as.factor(sigma), y= auc, fill=as.factor(sigma))) +
#           geom_boxplot() +
#           labs(subtitle = file)) %>% plot()
#
#
#   unperturbed_radon_point <- apply(t(data %>% filter(outliers==0, sigma==0) %>% .$params),1,mean)
#
#   data$radon_bias <- apply(data$params,1,function(x){euclidean_distance(x,unperturbed_radon_point)})
#
#
#   summary_data <- data %>%
#           group_by(outliers,sigma) %>%
#           reframe(
#                   mean_y = mean(radon_bias),
#                   ci_low = pmax(mean(radon_bias) - qt(0.975, df=n()-1) * sd(radon_bias) / sqrt(n()), min(radon_bias)),
#                   ci_high = pmin(mean(radon_bias) + qt(0.975, df=n()-1) * sd(radon_bias) / sqrt(n()), max(radon_bias))
#           )
#
#
#   (ggplot(summary_data %>% filter(sigma %in% c(0,1e-10,1e-5,0.001,0.1,0.5,1,2)), aes(x = outliers, y = mean_y)) +
#           geom_line(aes(color = as.factor(sigma))) +
#           geom_ribbon(aes(ymin = ci_low, ymax = ci_high, fill=as.factor(sigma)), alpha = 0.2) +
#           geom_vline(xintercept = 52, linetype="dashed") +
#           # geom_point(data = data, aes(x = x, y = y), alpha = 0.1) + # optional: to show original data points
#           labs(title = "Linear SVM Radon machine SUSY Dataset height=3",
#                subtitle = file,
#                x = "Number of outliers",
#                y = "Bias of radon point") +
#           theme_minimal())%>% plot()
#
#
#   (ggplot(data %>% filter(outliers == 0),
#          aes(x = as.factor(sigma), y= radon_bias, fill=as.factor(sigma))) +
#           geom_boxplot() +
#           labs(subtitle = file)) %>% plot()
#
#
#
# }

```



## Table summarizing the experiment results

```{r summary_table, eval = T, echo = F}

# full_data %>% filter("outliers" == 0)



auc_normal_data <- full_data %>%
        filter(experiment_name == "big_flip", sigma ==0, outliers == 0) %>%
        group_by(dataset,estimator,height) %>%
        reframe(auc_zero = mean(auc),auc_zero_std = sd(auc)) %>% mutate(auc= NULL)

auc_1000_data <- full_data %>%
        filter(experiment_name == "big_flip") %>%
        group_by(dataset,estimator,height,sigma,outliers) %>%
        reframe(auc_1000 = mean(auc), auc_1000_std = sd(auc)) %>% mutate(auc= NULL)



# min no until auc <.5
# for that auc avg +-

table_data <- full_data %>%
        filter(experiment_name == "big_flip",split == 0) %>%
        group_by(dataset,estimator,sigma,height,outliers) %>%
        reframe(auc = mean(auc), min_auc = min(auc)) %>%
        filter(min_auc > 0.5) %>%
        group_by(dataset,estimator,sigma,height) %>%
        filter(outliers == max(outliers)) %>%
        group_by(dataset,estimator,height) %>%
        filter((sigma == 0) | ((outliers == max(outliers)))) %>%
        slice_head(n=2) %>%
        mutate(noise = ifelse(sigma > 0,"sigma","0"), min_auc = NULL) %>%
        pivot_wider(names_from =noise, values_from = c(outliers,auc,sigma)) %>%
        left_join(auc_1000_data, by = join_by(estimator == estimator, dataset == dataset, outliers_0 == outliers, height==height, sigma_0 == sigma),suffix = c("","_0")) %>%
        left_join(auc_1000_data, by = join_by(estimator == estimator, dataset == dataset, outliers_0 == outliers, height==height, sigma_sigma == sigma),suffix = c("","_sigma")) %>%
        left_join(auc_normal_data) %>%
        ungroup() %>%
        transmute(
                  dataset=dataset,
                  d = ifelse(dataset == "SUSY", 19,ifelse(dataset == "sea50", 3,8)),
                  eps = 2^height,
                  height = height,
                  num_estimators = (d+2)^height,
                  model = estimator,
                  auc_zero = auc_zero,
                  auc_zero_std = auc_zero_std,
                  no.5 = outliers_0,
                  no.5.sigma = outliers_sigma,
                  auc_1000 = auc_1000,
                  auc_1000_std = auc_1000_std,
                  auc_1000.sigma = auc_1000_sigma,
                  auc_1000.sigma_std = auc_1000_std_sigma,
                  sigma = sigma_sigma
        )

write.csv(table_data,"final_table.csv")
table_data
# library(kableExtra)
#
# table_data
#
# library(kableExtra)
# library(dplyr)
# rows<- row.names(data_df)
#
# table_data %>%
#         mutate_all(function(x) format(x, digits = 3)) %>%
#         kbl(align = "r", , booktabs = TRUE, row.names = TRUE, format="latex")


```

## Summary Plot

```{r, echo=F, eval = T}
library(ggthemes)

summary_data <- full_data %>%
        filter(experiment_name == "big_flip", dataset == "SUSY", estimator == "SVM", sigma %in% c(0, 1e-3,1e-2,0.1,0.2,0.5)) %>%
        group_by(outliers,sigma) %>%
        filter(split == 0) %>%
        reframe(
                mean_auc = mean(auc),
                auc_low = (mean(auc) - qt(0.975, df=n()-1) * sd(auc) / sqrt(n())),
                auc_high = (mean(auc) + qt(0.975, df=n()-1) * sd(auc) / sqrt(n())),
                mean_radon_bias = mean(radon_bias,na.rm = TRUE),
                radon_bias_low = (mean(radon_bias,na.rm = TRUE) - qt(0.975, df=n()-1) * sd(radon_bias,na.rm = TRUE) / sqrt(n())),
                radon_bias_high = (mean(radon_bias,na.rm = TRUE) + qt(0.975, df=n()-1) * sd(radon_bias,na.rm = TRUE) / sqrt(n()))
        )


long_summary_data <-  summary_data %>%
        pivot_longer(cols = c(mean_auc, mean_radon_bias),
                     names_to = "measure",
                     values_to = "value") %>%
        mutate(high = ifelse(measure == "mean_auc",auc_high,radon_bias_high),
               low = ifelse(measure == "mean_auc",auc_low,radon_bias_low)) %>%
        mutate(y_min = 0, y_max = ifelse(measure=="mean_auc",1,30))


accessible_colors <- c(
        "#4477AA", "#EE6677", "#228833", "#CCBB44",
        "#66CCEE", "#AA3377", "#BBBBBB"
)


p <- ggplot(long_summary_data, aes(x=outliers, fill=as.factor(sigma))) +
        theme(panel.border = element_rect(color = "black")) +
        geom_line(aes(y=value,color = as.factor(sigma))) +
        geom_ribbon(aes(ymin = low, ymax = high),alpha = 0.2) +
        geom_blank(aes(y=y_min)) +
        geom_blank(aes(y=y_max)) +
        scale_color_manual(values = accessible_colors) +
        scale_fill_manual(values = accessible_colors) +
        facet_wrap(~measure,scales = "free_y",
                   strip.position = "left",
                   labeller = labeller(measure = c("mean_auc" = "ROC-AUC","mean_radon_bias" = "Distance to true center"))) +
        # geom_line(aes(y=mean_radon_bias/coeff+offset,color = as.factor(sigma))) +
        # geom_ribbon(aes(ymin = radon_bias_low/coeff+offset, ymax = radon_bias_high/coeff+offset),alpha = 0.2) +
        geom_vline(aes(xintercept = 52, linetype = "κ")) +
        xlim(0,1000) +
        labs(title = "Linear SVM Radon-machine on SUSY Dataset h=3",
             x = "Number of outliers",
             y = "",
             color = "additive noise (σ)",
             fill = "additive noise (σ)") +
        scale_linetype_manual(name="κ", labels = "", values= "dashed") +
        theme_minimal() +
        theme(legend.position = "bottom",
              legend.direction="horizontal",
              legend.text = element_text(size = 12),  # Adjust legend text size
              legend.key.width = unit(0.75, "cm"),  # Adjust width of legend keys (color boxes)
              legend.key.height = unit(0.5, "cm"),
              axis.text = element_text(size = 14),
              axis.title = element_text(size = 16),
              plot.title = element_text(size = 18, face = "bold"),
              strip.text = element_text(size = 16, vjust =2), # Left-align facet labels
              axis.text.y = element_text(size = 14, hjust = 0), # Right-align y-axis labels
              panel.grid.minor = element_blank(),
              # panel.grid.major = element_blank(),
              strip.placement = "outside",
               # Keep the panel border
              # panel.border = element_rect(color = "gray70", fill = NA, size=0.5),
              axis.ticks = element_line()) # Keep tick marks)


ggsave(file="test.svg", plot=p, width=32/3, height=6.5)
p
```




```{r}
data <- read.csv("results_aggregated/SUSY_SVM_break_2024-06-14_09:31:52.csv")
break_down_estimates <- data %>% group_by(outliers) %>% reframe(break_prob = mean(auc<0.5))
plot(break_down_estimates)
break_down_estimates
```